# Generated by Django 4.2.4 on 2023-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('is_public', models.BooleanField()),
                ('file_url', models.TextField()),
                ('solve_percentage', models.JSONField()),
                ('points', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
