# Generated by Django 4.2.4 on 2023-09-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissectix', '0003_alter_challenge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='chall_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='functions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='file_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
