# Generated by Django 4.2.4 on 2023-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissectix', '0004_challenge_chall_id_challenge_functions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='chall_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
