# Generated by Django 4.2.4 on 2023-09-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissectix', '0005_alter_challenge_chall_id_alter_challenge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
