# Generated by Django 4.2.4 on 2023-09-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissectix', '0007_challenge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
    ]
