# Generated by Django 4.2.4 on 2023-09-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissectix', '0008_challenge_solve_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='solve_count',
        ),
    ]
