# Generated by Django 4.2.4 on 2023-08-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('is_public', models.BooleanField()),
                ('file_url', models.TextField()),
                ('solve_percentage', models.JSONField()),
                ('points', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DissectixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.IntegerField()),
                ('attempted_challenges', models.JSONField()),
                ('created_challenges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chall_author', to='authserver.challenge')),
            ],
        ),
    ]
