# Generated by Django 4.2.4 on 2023-08-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0002_alter_challenge_name_alter_dissectixuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissectixuser',
            name='attempted_challenges',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dissectixuser',
            name='created_challenges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chall_author', to='authserver.challenge'),
        ),
        migrations.AlterField(
            model_name='dissectixuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='dissectixuser',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
