# Generated by Django 4.2.4 on 2023-09-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0003_alter_dissectixuser_attempted_challenges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissectixuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dissectixuser',
            name='password',
        ),
    ]
