# Generated by Django 4.2.4 on 2023-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0005_alter_dissectixuser_created_challenges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissectixuser',
            name='attempted_challenges',
        ),
        migrations.AddField(
            model_name='dissectixuser',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
    ]
