# Generated by Django 4.2.4 on 2023-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0006_remove_dissectixuser_attempted_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissectixuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
