# Generated by Django 4.2.4 on 2023-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0007_alter_dissectixuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissectixuser',
            name='solved_challenges',
            field=models.JSONField(default={}),
        ),
    ]
