# Generated by Django 4.2.4 on 2023-09-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0009_alter_dissectixuser_solved_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissectixuser',
            name='created_challenges',
            field=models.JSONField(default=dict),
        ),
    ]
