version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4050:8000"
    volumes:
      - dissectix-db:/server/db.sqlite3

volumes:
  dissectix-db: